import Link from "next/link";
import { ArrowRight, BookOpen, Plus } from "lucide-react";
import { articles } from "@/lib/resources";

const faqs = [
  ["Was ist MIND?", "MIND gibt dir Raum, dich selbst besser zu verstehen. Entdecke psychologisches Wissen, reflektiere eigene Erfahrungen und finde neue Perspektiven für deinen Alltag. Du beginnst mit dem, was dich beschäftigt, und wählst eine KI-Begleitung, deren Gesprächsstil zu dir passt."],
  ["Ist MIND eine Therapie oder stellt es Diagnosen?", "Nein. MIND bietet weder Psychotherapie noch medizinische Diagnostik oder Behandlung an. Es stellt keine Erkrankungen fest und gibt keine Behandlungsempfehlungen. Inhalte und Selbsteinschätzungen ersetzen keine ärztliche oder psychotherapeutische Abklärung. MIND verspricht keine Heilung oder Linderung einer Erkrankung."],
  ["Mit welchen Themen kann ich MIND nutzen?", "Zum Beispiel mit Gedanken, die dich beschäftigen, alltäglichem Stress, Selbstzweifeln, Beziehungen, Veränderungen oder Fragen zu deinen Bedürfnissen. Auch Aufmerksamkeit und innere Unruhe können Themen zum Verstehen sein. Daraus leitet MIND keine Diagnose ab. Bei anhaltenden oder starken Beschwerden ist professionelle Unterstützung der passende nächste Ansprechpartner."],
  ["Auf welcher wissenschaftlichen Basis arbeitet MIND?", "Nachvollziehbare Fachquellen bilden die Grundlage unserer Wissensartikel. Du findest die verwendete Literatur und den Recherchestand direkt beim Beitrag. Wir unterscheiden allgemeines psychologisches Wissen von persönlichen Reflexionsfragen und benennen die Grenzen der Inhalte. Erkenntnisse über einzelne Konzepte sind kein Wirksamkeitsnachweis für MIND."],
  ["Welche Haltung haben die Avatare?", "Aufmerksamkeit, Respekt und professionelle emotionale Distanz bestimmen die Haltung von MIND. Unsere KI-Avatare stehen für unterschiedliche Gesprächsstile: ruhig und einfühlsam, klar und anregend oder offen und neugierig. Du entscheidest, was du teilen und welche Perspektiven du aufgreifen möchtest. KI-Aussagen sind keine fachliche Beurteilung deiner Person."],
  ["Muss ich Ziele setzen oder Aufgaben erledigen?", "Nein. Verstehen darf für sich stehen. Wenn du ein Vorhaben besprechen möchtest, gehört auch die Planung ins Gespräch. Es gibt keine Aufgabenpflicht und keine Bewertung deiner Fortschritte. Du bestimmst das Tempo und darfst etwas ändern, pausieren oder loslassen."],
  ["Warum ist fachliche Transparenz wichtig?", "Eine Anregung soll verständlich sein: Woher stammt das Konzept? Was lässt sich daraus lernen? Und welche Grenzen hat es? Das ist unser Maßstab für Psychoedukation. Auch Wissen aus therapeutischen Fachrichtungen wird als Lerninhalt eingeordnet. Daraus entsteht keine Therapie oder persönliche Behandlungsempfehlung."],
  ["Können Selbsteinschätzungen ADHS oder andere Erkrankungen feststellen?", "Nein. Die aktuelle Reflexion zu Aufmerksamkeit hilft dir, Beobachtungen zu sammeln. Sie ist kein validierter ADHS-Test und liefert weder einen Punktwert noch eine Diagnose. Auch ein validiertes Screening könnte eine Erkrankung weder sicher bestätigen noch ausschließen. Diagnostische Fragen gehören in eine fachliche Abklärung."],
  ["Werden meine Eingaben zum Training von KI-Modellen genutzt?", "Deine Eingaben im Gesprächseinstieg und in der Selbsteinschätzung werden nicht an einen KI-Anbieter übermittelt und nicht zum Training von Sprachmodellen genutzt. MIND speichert diese Inhalte nicht dauerhaft. Was mit Kontodaten und freiwilligen Angaben geschieht, erklären wir in den Datenschutzhinweisen."],
  ["Welche Daten speichert MIND?", "Für dein Konto speichern wir deine E-Mail-Adresse, Einstellungen und technische Anmeldedaten. Eine Telefonnummer ist nur erforderlich, wenn du sie freiwillig für WhatsApp hinterlegen möchtest. Eingaben im Gesprächseinstieg und in der Selbsteinschätzung bleiben in der geöffneten Ansicht und werden beim Verlassen oder Neuladen verworfen."],
  ["Was sieht die Administration von mir?", "Die Adminoberfläche zeigt Konten, technische Nutzungszahlen und vorhandene Zahlungsinformationen. Sie enthält keine Gesprächsinhalte, Themen, Antworten aus Selbsteinschätzungen oder Telefonnummern. Kreditkarten werden ausschließlich über Kartenmarke, letzte vier Ziffern und Ablaufdatum dargestellt. Einzelheiten zu Verarbeitung und Zugriffsrechten findest du unter Datenschutz."],
  ["Wie behalte ich die Kontrolle über meine Angaben?", "In Mein Bereich verwaltest du deine WhatsApp-Einwilligung und kannst sie jederzeit widerrufen. Dabei wird deine Telefonnummer aus dem Profil entfernt. Dort kannst du auch alle eigenen Sitzungen beenden. Antworten in der Selbsteinschätzung lassen sich sofort zurücksetzen. Informationen zu Kontolöschung, Datenexport und deinen Rechten stehen in den Datenschutzhinweisen."],
];

export function ResourceCards() {
  return <div className="resource-grid">{articles.map((article, index) => <Link className={`resource-card resource-${index}`} href={`/resources/${article.slug}`} key={article.slug}><span className="resource-visual" aria-hidden="true"><BookOpen size={34} strokeWidth={1}/><span>0{index + 1}</span></span><span className="eyebrow">WISSEN · {article.category}</span><h3>{article.title}</h3><p>{article.summary}</p><span className="text-link">Artikel lesen <ArrowRight size={16}/></span></Link>)}<Link className="resource-card resource-reflection" href="/resources/selbsteinschaetzung"><span className="resource-visual" aria-hidden="true"><span className="reflection-mark">?</span><span>03</span></span><span className="eyebrow">SELBSTEINSCHÄTZUNG · OHNE DIAGNOSE</span><h3>Wie erlebe ich meine Aufmerksamkeit?</h3><p>Ein paar Fragen, um Beobachtungen zu sortieren. Ohne Bewertung oder ADHS-Punktwert.</p><span className="text-link">In Ruhe reflektieren <ArrowRight size={16}/></span></Link></div>;
}

export function HomeInformation() {
  return <div className="home-information"><section className="resources-section" id="resources" aria-labelledby="resources-heading"><div className="information-heading"><div><span className="eyebrow">RESSOURCES</span><h2 id="resources-heading">Ein bisschen mehr verstehen.</h2><p>Wissen und Fragen, die dir Raum zum Nachdenken geben.</p></div><Link className="text-link" href="/resources">Alle Ressourcen <ArrowRight size={16}/></Link></div><ResourceCards/></section><section className="faq-section" id="faq" aria-labelledby="faq-heading"><div className="faq-intro"><span className="eyebrow">GUT ZU WISSEN</span><h2 id="faq-heading">Raum für Fragen.<br/><em>Klare Antworten.</em></h2><p>Psychoedukation. Selbstreflexion. Ein verständnisvoller Begleiter.</p><p>Keine Therapie. Keine Diagnose.</p><Link className="text-link" href="/privacy">Datenschutz im Detail <ArrowRight size={16}/></Link></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true"/></summary><p>{answer}</p></details>)}<details><summary>Ist MIND für Krisen oder Notfälle geeignet?<Plus size={18} aria-hidden="true"/></summary><p>Nein. MIND ist kein Krisendienst; hier überwacht niemand deine Eingaben. Bei unmittelbarer Gefahr wähle in Deutschland <a href="tel:112">112</a>. Die <a href="https://www.telefonseelsorge.de/telefon/" rel="noreferrer">TelefonSeelsorge</a> ist unter <a href="tel:116123">116 123</a> rund um die Uhr kostenlos erreichbar. Außerhalb Deutschlands nutze die örtlichen Notfallangebote.</p></details></div></section></div>;
}
