import Link from "next/link";
import { ArrowRight, BookOpen, Plus } from "lucide-react";
import { articles } from "@/lib/resources";

const faqs = [
  ["Was ist MIND?", "MIND ist ein Angebot für Psychoedukation und Selbstreflexion: psychologisches Wissen verständlich machen, eigene Erfahrungen einordnen und neue Perspektiven entdecken. Im Mittelpunkt steht ein Gespräch mit einem KI-Avatar. Aktuell kannst du den Einstieg ausprobieren; echte KI-Gespräche sind noch nicht verfügbar."],
  ["Ist MIND eine Therapie oder stellt es Diagnosen?", "Nein. MIND bietet weder Psychotherapie noch medizinische Diagnostik oder Behandlung an. Es stellt keine Erkrankungen fest und gibt keine Behandlungsempfehlungen. Inhalte und Selbsteinschätzungen ersetzen keine ärztliche oder psychotherapeutische Abklärung. MIND verspricht keine Heilung oder Linderung einer Erkrankung."],
  ["Mit welchen Themen kann ich MIND nutzen?", "Zum Beispiel mit Gedanken, die dich beschäftigen, alltäglichem Stress, Selbstzweifeln, Beziehungen, Veränderungen oder Fragen zu deinen Bedürfnissen. Auch Aufmerksamkeit und innere Unruhe können Themen zum Verstehen sein. Daraus leitet MIND keine Diagnose ab. Bei anhaltenden oder starken Beschwerden ist professionelle Unterstützung der passende nächste Ansprechpartner."],
  ["Auf welcher wissenschaftlichen Basis arbeitet MIND?", "Unser Anspruch ist eine fundierte Literaturrecherche mit nachvollziehbaren Quellen: Leitlinien, wissenschaftliche Übersichtsarbeiten und qualitätsgesicherte Fachinformationen. Die ersten Artikel verlinken ihre jeweilige Grundlage. Die umfassende Wissensbasis und fachliche Prüfung für die spätere Gesprächsfunktion sind noch im Aufbau. Für MIND selbst liegt derzeit kein Wirksamkeitsnachweis vor."],
  ["Welche Haltung haben die Avatare?", "Sie sollen aufmerksam, empathisch und respektvoll begleiten und dabei professionelle emotionale Distanz bewahren. Sie sind als KI erkennbar und übernehmen keine Rolle als Freund oder Therapeut. Du bestimmst, was du teilen und welche Anregungen du aufgreifen möchtest. KI kann sich irren; ihre Aussagen sind keine fachliche Beurteilung deiner Person."],
  ["Muss ich Ziele setzen oder Aufgaben erledigen?", "Nein. Ein Gespräch darf einfach dem Verstehen dienen. Wenn du ein Vorhaben besprechen möchtest, bleibt auch die Planung im Gespräch. Das spätere Erinnern und behutsame Nachfragen erfolgt mit deiner Zustimmung. Du kannst etwas ändern, pausieren oder loslassen. Erinnerungen sind in dieser Vorschau noch nicht aktiv."],
  ["Können Selbsteinschätzungen ADHS oder andere Erkrankungen feststellen?", "Nein. Die aktuelle Reflexion zu Aufmerksamkeit hilft dir, Beobachtungen zu sammeln. Sie ist kein validierter ADHS-Test und liefert weder einen Punktwert noch eine Diagnose. Auch ein validiertes Screening könnte eine Erkrankung weder sicher bestätigen noch ausschließen. Diagnostische Fragen gehören in eine fachliche Abklärung."],
  ["Werden meine Gespräche zum Training von KI-Modellen genutzt?", "In dieser Vorschau werden deine Gesprächseingaben nicht versendet und nicht für Modelltraining verwendet. Es ist kein KI-Anbieter angeschlossen. Für den späteren Betrieb gilt unsere Vorgabe: Gesprächsinhalte dürfen weder von MIND noch von eingesetzten Anbietern zum Training von Sprachmodellen genutzt werden. Die vertragliche und technische Absicherung muss vor der Freigabe nachgewiesen sein."],
  ["Welche Daten speichert MIND – und wie sicher sind sie?", "Themen-Eingaben und Antworten in der Selbsteinschätzung bleiben aktuell nur im Zustand der geöffneten Ansicht und werden nicht an unseren Server gesendet. Eine Anmeldung speichert Kontodaten und technische Sitzungsdaten. Geschützte Seiten erfordern eine Anmeldung. Das ist keine Garantie vollständiger Sicherheit: Die Prüfung der Produktionsumgebung steht noch aus. Bitte nutze die Entwicklungsfassung nicht für sensible persönliche Inhalte."],
  ["Wer kann meine Daten sehen und wo werden sie verarbeitet?", "Derzeit läuft MIND als lokale Entwicklungsfassung; es gibt keinen angeschlossenen KI-Dienst und kein Werbetracking. Ein Produktionsstandort, Dienstleister und deren Zugriffsrechte sind noch nicht abschließend festgelegt. Vor dem öffentlichen Start müssen wir diese Angaben, mögliche Übermittlungen in Drittländer und Schutzmaßnahmen konkret offenlegen. Wir versprechen deshalb derzeit weder ausschließliches EU-Hosting noch Ende-zu-Ende-Verschlüsselung."],
  ["Kann ich Daten löschen, exportieren oder eine Einwilligung widerrufen?", "Die Selbsteinschätzung lässt sich sofort zurücksetzen; Gesprächseingaben verschwinden beim Verlassen oder Neuladen der Ansicht. Für gespeicherte Kontodaten fehlen noch die Funktionen für Export und Löschung sowie der veröffentlichte Datenschutzkontakt. Vor dem öffentlichen Start müssen die Ausübung deiner Datenschutzrechte, Aufbewahrungsfristen und gegebenenfalls der Widerruf von Einwilligungen geregelt sein. Diese FAQ ersetzt keine vollständige Datenschutzerklärung."],
];

export function ResourceCards() {
  return <div className="resource-grid">{articles.map((article, index) => <Link className={`resource-card resource-${index}`} href={`/resources/${article.slug}`} key={article.slug}><span className="resource-visual" aria-hidden="true"><BookOpen size={34} strokeWidth={1}/><span>0{index + 1}</span></span><span className="eyebrow">WISSEN · {article.category}</span><h3>{article.title}</h3><p>{article.summary}</p><span className="text-link">Artikel lesen <ArrowRight size={16}/></span></Link>)}<Link className="resource-card resource-reflection" href="/resources/selbsteinschaetzung"><span className="resource-visual" aria-hidden="true"><span className="reflection-mark">?</span><span>03</span></span><span className="eyebrow">SELBSTEINSCHÄTZUNG · OHNE DIAGNOSE</span><h3>Wie erlebe ich meine Aufmerksamkeit?</h3><p>Ein paar Fragen, um Beobachtungen zu sortieren. Ohne Bewertung oder ADHS-Punktwert.</p><span className="text-link">In Ruhe reflektieren <ArrowRight size={16}/></span></Link></div>;
}

export function HomeInformation() {
  return <div className="home-information"><section className="resources-section" id="resources" aria-labelledby="resources-heading"><div className="information-heading"><div><span className="eyebrow">RESSOURCES</span><h2 id="resources-heading">Ein bisschen mehr verstehen.</h2><p>Wissen und Fragen, die dir Raum zum Nachdenken geben.</p></div><Link className="text-link" href="/resources">Alle Ressourcen <ArrowRight size={16}/></Link></div><ResourceCards/></section><section className="faq-section" id="faq" aria-labelledby="faq-heading"><div className="faq-intro"><span className="eyebrow">GUT ZU WISSEN</span><h2 id="faq-heading">Raum für Fragen.<br/><em>Klare Antworten.</em></h2><p>Psychoedukation. Selbstreflexion. Ein verständnisvoller Begleiter.</p><p>Keine Therapie. Keine Diagnose.</p><Link className="text-link" href="/privacy">Datenschutz im Detail <ArrowRight size={16}/></Link></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true"/></summary><p>{answer}</p></details>)}<details><summary>Ist MIND für Krisen oder Notfälle geeignet?<Plus size={18} aria-hidden="true"/></summary><p>Nein. MIND ist kein Krisendienst; hier überwacht niemand deine Eingaben. Bei unmittelbarer Gefahr wähle in Deutschland <a href="tel:112">112</a>. Die <a href="https://www.telefonseelsorge.de/telefon/" rel="noreferrer">TelefonSeelsorge</a> ist unter <a href="tel:116123">116 123</a> rund um die Uhr kostenlos erreichbar. Außerhalb Deutschlands nutze die örtlichen Notfallangebote.</p></details></div></section></div>;
}
