"use client";
import { useState } from "react";
const prompts = ["In welchen Situationen fällt es mir schwer, bei einer Sache zu bleiben?", "Wann gelingt mir Konzentration leichter – und was ist dann anders?", "Seit wann nehme ich das wahr, und wie beeinflusst es meinen Alltag?", "Welche Fragen möchte ich dazu mit einer Fachperson besprechen?"];
export function SelfReflection() {
  const [answers, setAnswers] = useState<string[]>(prompts.map(() => ""));
  const [showSummary, setShowSummary] = useState(false);
  const [reset, setReset] = useState(false);
  return <div className="reflection-form"><p className="reflection-privacy">Deine Antworten werden nicht gesendet oder dauerhaft gespeichert. Du kannst jede Frage auslassen. Beim Neuladen oder Verlassen dieser Ansicht werden sie verworfen.</p><form onSubmit={event => { event.preventDefault(); setShowSummary(true); }}>{prompts.map((prompt, index) => <div className="reflection-question" key={prompt}><label htmlFor={`reflection-${index}`}><span>0{index + 1}</span>{prompt}</label><textarea id={`reflection-${index}`} rows={3} maxLength={1500} value={answers[index]} placeholder="Wenn du möchtest, halte ein paar Gedanken fest …" onChange={event => { setAnswers(answers.map((answer, i) => i === index ? event.target.value : answer)); setShowSummary(false); setReset(false); }}/></div>)}<div className="reflection-actions"><button className="button" type="submit">Meine Beobachtungen ansehen</button><button className="button secondary" type="button" onClick={() => { setAnswers(prompts.map(() => "")); setShowSummary(false); setReset(true); }}>Antworten zurücksetzen</button></div></form><div aria-live="polite">{reset && <p>Deine Antworten wurden aus dieser Ansicht entfernt.</p>}{showSummary && <section className="reflection-summary"><h2>Deine Beobachtungen</h2><p>Diese Zusammenstellung enthält nur deine eigenen Worte. Es gibt keine Bewertung, keinen Punktwert und keine Aussage darüber, ob du ADHS hast oder nicht.</p>{answers.some(answer => answer.trim()) ? <dl>{answers.map((answer, index) => answer.trim() && <div key={prompts[index]}><dt>{prompts[index]}</dt><dd>{answer}</dd></div>)}</dl> : <p>Du hast noch nichts eingetragen. Auch ohne Antworten kannst du die Fragen für dich mitnehmen.</p>}<p>Wenn dich Schwierigkeiten anhaltend belasten, kann eine ärztliche oder psychotherapeutische Abklärung helfen. Deine Notizen können ein Ausgangspunkt für dieses Gespräch sein.</p></section>}</div></div>;
}
