import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { currentUser } from "@/lib/auth/session";
import { isAdminEmail } from "@/lib/admin/policy";
import { listAdminUsers } from "@/lib/admin/users";
import { AppShell } from "@/components/app-shell";
import { BillingDetails } from "@/components/billing-details";
export const dynamic = "force-dynamic";
export const metadata = { title: "Nutzerverwaltung", robots: { index: false, follow: false } };
export default async function Users({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const current = await currentUser(); if (!current) redirect("/login"); if (!current.emailVerified || !isAdminEmail(current.email)) notFound();
  const params = await searchParams; const q = (params.q ?? "").trim().slice(0, 200); const page = Math.max(1, Math.min(10000, Math.floor(Number(params.page) || 1)));
  const { users, count } = await listAdminUsers(q, page);
  const statuses: Record<string, string> = { ACTIVE: "Aktiv", SUSPENDED: "Gesperrt", DELETION_PENDING: "Löschung vorgemerkt", DELETED: "Gelöscht" };
  return <AppShell admin><div className="admin-page"><nav className="admin-subnav" aria-label="Administration"><Link href="/admin">Gesprächsgrundlage</Link><Link href="/admin/users" aria-current="page">Nutzer & Nutzung</Link></nav><header className="admin-heading"><span className="eyebrow">ADMINISTRATION · NUTZER</span><h1>Nutzung im Blick.<br/>Gespräche bleiben privat.</h1><p>Konten, technische Nutzungszahlen und Zahlungsübersicht. Diese Ansicht enthält keine Gesprächsinhalte, Themen, Selbsteinschätzungen oder Telefonnummern.</p></header><form className="user-search" action="/admin/users"><label htmlFor="user-search">Nach E-Mail-Adresse suchen</label><div><input id="user-search" name="q" type="search" defaultValue={q} maxLength={200}/><button className="button" type="submit">Suchen</button></div></form><p className="subtle">{count} Konten · Seite {page} von {Math.max(1, Math.ceil(count / 20))}</p><p className="admin-boundary">Anmeldungen werden seit Einführung dieser Übersicht gezählt. KI-Nutzungszahlen und Zahlungen werden erst mit den jeweiligen Diensten erfasst.</p>{!users.length && <div className="admin-empty">Keine passenden Konten gefunden.</div>}{users.map(user => <article className="admin-panel admin-user" key={user.id}><div className="admin-panel-heading"><h2>{user.email}</h2><span className="pill">{statuses[user.status]}</span></div><p className="subtle">Registriert am {user.createdAt.toLocaleDateString("de-DE")}</p><dl className="usage-grid"><div><dt>Anmeldungen</dt><dd>{user.loginCount}</dd></div><div><dt>Letzte Anmeldung</dt><dd>{user.lastLoginAt?.toLocaleString("de-DE") ?? "Noch nicht erfasst"}</dd></div><div><dt>KI-Gespräche / Nachrichten</dt><dd>{user.usage ? `${user.usage.conversations} / ${user.usage.messages}` : "Noch nicht erfasst"}</dd></div><div><dt>Tokens / letzte KI-Nutzung</dt><dd>{user.usage ? `${user.usage.tokens} / ${user.usage.lastUsedAt?.toLocaleString("de-DE") ?? "–"}` : "Noch nicht erfasst"}</dd></div></dl><details className="admin-billing"><summary>Zahlungen & Karten · {user._count.payments} Zahlungen</summary><BillingDetails cards={user.cards} payments={user.payments.map(payment => ({ ...payment, createdAt: payment.createdAt.toISOString(), paidAt: payment.paidAt?.toISOString() ?? null }))}/>{user._count.payments > 5 && <p className="subtle">Angezeigt werden die letzten fünf Zahlungen.</p>}</details></article>)}<nav className="pagination" aria-label="Nutzerseiten">{page > 1 && <Link className="button secondary" href={`/admin/users?q=${encodeURIComponent(q)}&page=${page - 1}`}>← Zurück</Link>}{page * 20 < count && <Link className="button secondary" href={`/admin/users?q=${encodeURIComponent(q)}&page=${page + 1}`}>Weiter →</Link>}</nav></div></AppShell>;
}
